package com.finallygo.test.pojo;


/**
 * AClrCoAllResultRate generated by MyEclipse - Hibernate Tools
 */

public class AClrCoAllResultRate   {


    // Fields    

     private AClrCoAllResultRateId id;
     private String endDate;
     private Double lossFactor;
     private Double weightLossFactor;
     private Double rateValue;
     private Double loanBalance;
     private Double reservBalance;
     private String composeName;
     private String resultType;


    // Constructors

    public String getComposeName() {
		return composeName;
	}

	public void setComposeName(String composeName) {
		this.composeName = composeName;
	}

	/** default constructor */
    public AClrCoAllResultRate() {
    }

	/** minimal constructor */
    public AClrCoAllResultRate(AClrCoAllResultRateId id) {
        this.id = id;
    }
    
    /** full constructor */
    public AClrCoAllResultRate(AClrCoAllResultRateId id, String classifyType, String endDate, Double lossFactor, Double weightLossFactor, Double rateValue, Double loanBalance, Double reservBalance) {
        this.id = id;
        this.endDate = endDate;
        this.lossFactor = lossFactor;
        this.weightLossFactor = weightLossFactor;
        this.rateValue = rateValue;
        this.loanBalance = loanBalance;
        this.reservBalance = reservBalance;
    }

   
    // Property accessors

    public AClrCoAllResultRateId getId() {
        return this.id;
    }
    
    public void setId(AClrCoAllResultRateId id) {
        this.id = id;
    }

    public String getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(String endDate) {
        this.endDate = endDate;
    }

    public Double getLossFactor() {
        return this.lossFactor;
    }
    
    public void setLossFactor(Double lossFactor) {
        this.lossFactor = lossFactor;
    }

    public Double getWeightLossFactor() {
        return this.weightLossFactor;
    }
    
    public void setWeightLossFactor(Double weightLossFactor) {
        this.weightLossFactor = weightLossFactor;
    }

    public Double getRateValue() {
        return this.rateValue;
    }
    
    public void setRateValue(Double rateValue) {
        this.rateValue = rateValue;
    }

    public Double getLoanBalance() {
        return this.loanBalance;
    }
    
    public void setLoanBalance(Double loanBalance) {
        this.loanBalance = loanBalance;
    }

    public Double getReservBalance() {
        return this.reservBalance;
    }
    
    public void setReservBalance(Double reservBalance) {
        this.reservBalance = reservBalance;
    }

	public String getResultType() {
		return resultType;
	}

	public void setResultType(String resultType) {
		this.resultType = resultType;
	}
   







}