package com.finallygo.test.pojo;



/**
 * AClrCoAllResultRateId generated by MyEclipse - Hibernate Tools
 */

public class AClrCoAllResultRateId  {


    // Fields    

     private String jobNo;
     private String composeCode;
     private String classifyType;

    // Constructors

    public String getClassifyType() {
		return classifyType;
	}


	public void setClassifyType(String classifyType) {
		this.classifyType = classifyType;
	}


	/** default constructor */
    public AClrCoAllResultRateId() {
    }

    
    /** full constructor */
    public AClrCoAllResultRateId(String jobNo, String composeCode) {
        this.jobNo = jobNo;
        this.composeCode = composeCode;
    }

   
    // Property accessors

    public String getJobNo() {
        return this.jobNo;
    }
    
    public void setJobNo(String jobNo) {
        this.jobNo = jobNo;
    }

    public String getComposeCode() {
        return this.composeCode;
    }
    
    public void setComposeCode(String composeCode) {
        this.composeCode = composeCode;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AClrCoAllResultRateId) ) return false;
		 AClrCoAllResultRateId castOther = ( AClrCoAllResultRateId ) other; 
         
		 return ( (this.getJobNo()==castOther.getJobNo()) || ( this.getJobNo()!=null && castOther.getJobNo()!=null && this.getJobNo().equals(castOther.getJobNo()) ) )
 && ( (this.getComposeCode()==castOther.getComposeCode()) || ( this.getComposeCode()!=null && castOther.getComposeCode()!=null && this.getComposeCode().equals(castOther.getComposeCode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getJobNo() == null ? 0 : this.getJobNo().hashCode() );
         result = 37 * result + ( getComposeCode() == null ? 0 : this.getComposeCode().hashCode() );
         return result;
   }   




	public String toString() {
		return this.getJobNo();
	}
}